### ISSUE TITLE
Trouble importing bats.py

### ISSUE THREAD

**Issue by cocount57** [bnels/BATS.py#2]
Hello! 
I successfully (I hope) installed bats.py into new conda env as in the tutorial, but when i try to "import bats" or "from bats import bats" i get these:

/home/cocount/anaconda3/envs/bats/bin/python /home/cocount/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "/home/cocount/PycharmProjects/pythonProject/main.py", line 1, in <module>
    from bats import bats
  File "/home/cocount/anaconda3/envs/bats/lib/python3.9/site-packages/bats-0.0.0-py3.9-linux-x86_64.egg/bats/__init__.py", line 5, in <module>
    from .visualization import persistence_diagram, persistence_barcode
  File "/home/cocount/anaconda3/envs/bats/lib/python3.9/site-packages/bats-0.0.0-py3.9-linux-x86_64.egg/bats/visualization/__init__.py", line 1, in <module>
    from .visualization import *
  File "/home/cocount/anaconda3/envs/bats/lib/python3.9/site-packages/bats-0.0.0-py3.9-linux-x86_64.egg/bats/visualization/visualization.py", line 66
    ax.set_xlim((*xbnds))
                 ^
SyntaxError: can't use starred expression here

Process finished with exit code 1

I use PyCharm on Ubuntux64 in VB on windows7, i don't know if it is an issue with the package or install.

**Comment by bnels** [comment]
@cocount57 Sorry for the delayed response. Are you still observing this issue or have you resolved it?

I think this may be something that changed in Python 3.9 (I'm running Python 3.7).  My hunch is that this will be resolved by just setting `xbnds` to a tuple and passing it directly instead of using the starred expression.

**Comment by bnels** [comment]
I've pushed a commit which does this here:
https://github.com/bnels/BATS.py/commit/af7e8f3e43e7ab8bb0fe47c9d7117ded3d0f32b3

Please let me know if this resolves the issue.

**Comment by bnels** [comment]
In 5f28d5d40fa1eea72771213d691d740d15816c15 I implemented CI for Ubuntu and MacOS on Python 3.7, 3.8, and 3.9.

Build and tests are passing, and this issue appears to be resolved.  Please open a new issue for any future installation problems.
